Updated code to fit new omarchy-menu

diff --git a/bin/omarchy-plugin-install b/bin/omarchy-plugin-install
--- a/bin/omarchy-plugin-install
+++ b/bin/omarchy-plugin-install
@@ -1,24 +1,26 @@
 #!/bin/bash
 
-if [ -z "$1" ]; then
-  echo "Usage: omarchy-plugin-install <plugin-repo-url>"
-  exit 1
-fi
-
 PLUGIN_REPO_URL="$1"
-PLUGIN_PATH="$HOME/.config/omarchy/plugins"
-PLUGIN_NAME=$(basename -s .git "$PLUGIN_REPO_URL")
 
-echo -e "\n\e[32mInstalling plugin: $PLUGIN_NAME\e[0m"
-
-if ! mkdir -p "$PLUGIN_PATH" || ! git clone "$PLUGIN_REPO_URL" "$PLUGIN_PATH/$PLUGIN_NAME"; then
-  echo "Error: Failed to clone the plugin repo."
-  exit 1
+if [[ -z "$1" ]]; then
+  PLUGIN_REPO_URL=$(gum input --placeholder="Git repo URL for plugin" --header="")
 fi
 
-cd "$PLUGIN_PATH/$PLUGIN_NAME"
+if [[ -n "$PLUGIN_REPO_URL" ]]; then
+  PLUGIN_PATH="$HOME/.config/omarchy/plugins"
+  PLUGIN_NAME=$(basename -s .git "$PLUGIN_REPO_URL")
 
-# Running the plugins install command
-./install.sh
+  echo -e "\n\e[32mInstalling plugin: $PLUGIN_NAME\e[0m"
 
-notify-send "Plugin: $PLUGIN_NAME has been installed" -t 2000
+  if ! mkdir -p "$PLUGIN_PATH" || ! git clone "$PLUGIN_REPO_URL" "$PLUGIN_PATH/$PLUGIN_NAME"; then
+    echo "Error: Failed to clone the plugin repo."
+    exit 1
+  fi
+
+  cd "$PLUGIN_PATH/$PLUGIN_NAME"
+
+  # Running the plugins install script
+  ./install
+
+  ~/.local/share/omarchy/bin/omarchy-show-done
+fi
diff --git a/bin/omarchy-plugin-remove b/bin/omarchy-plugin-remove
--- a/bin/omarchy-plugin-remove
+++ b/bin/omarchy-plugin-remove
@@ -1,23 +1,23 @@
 #!/bin/bash
 
-if [ -z "$1" ]; then
-  echo "Usage: omarchy-plugin-remove <plugin-name>"
-  exit 1
-fi
-
-PLUGIN_PATH="$HOME/.config/omarchy/plugins"
 PLUGIN_NAME="$1"
+PLUGIN_PATH="$HOME/.config/omarchy/plugins"
 
-echo -e "\n\e[31mRemoving plugin: $PLUGIN_NAME\e[0m"
-
-if [ ! -d "$PLUGIN_PATH/$PLUGIN_NAME" ]; then
-  echo "Error: Plugin '$PLUGIN_NAME' not found."
-  exit 1
+if [[ -z "$1" ]]; then
+  PLUGIN_NAME=$(basename -a "$HOME/.config/omarchy/plugins"/* | fzf "${fzf_args[@]}")
 fi
 
-cd "$PLUGIN_PATH/$PLUGIN_NAME"
+if [[ -n "$PLUGIN_NAME" ]]; then
+  echo -e "\n\e[31mRemoving plugin: $PLUGIN_NAME\e[0m"
 
-# Running the plugins install command
-./remove.sh
+  if [ ! -d "$PLUGIN_PATH/$PLUGIN_NAME" ]; then
+    echo "Error: Plugin '$PLUGIN_NAME' not found."
+    exit 1
+  fi
 
-notify-send "Plugin: $PLUGIN_NAME has been removed" -t 2000
+  # Running the plugins remove script
+  "$PLUGIN_PATH/$PLUGIN_NAME/remove"
+  rm -rf "$PLUGIN_PATH/$PLUGIN_NAME"
+
+  ~/.local/share/omarchy/bin/omarchy-show-done
+fi
diff --git a/bin/omarchy-plugin-update b/bin/omarchy-plugin-update
--- a/bin/omarchy-plugin-update
+++ b/bin/omarchy-plugin-update
@@ -1,23 +1,24 @@
 #!/bin/bash
 
-if [ -z "$1" ]; then
-  echo "Usage: omarchy-plugin-update <plugin-name>"
-  exit 1
-fi
-
-PLUGIN_PATH="$HOME/.config/omarchy/plugins"
 PLUGIN_NAME="$1"
+PLUGIN_PATH="$HOME/.config/omarchy/plugins"
 
-echo -e "\n\e[33mUpdating plugin: $PLUGIN_NAME\e[0m"
-
-if [ ! -d "$PLUGIN_PATH/$PLUGIN_NAME" ]; then
-  echo "Error: Plugin '$PLUGIN_NAME' not found."
-  exit 1
+if [[ -z "$1" ]]; then
+  PLUGIN_NAME=$(basename -a "$HOME/.config/omarchy/plugins"/* | fzf "${fzf_args[@]}")
 fi
 
-cd "$PLUGIN_PATH/$PLUGIN_NAME"
+if [[ -n "$PLUGIN_NAME" ]]; then
+  echo -e "\n\e[33mUpdating plugin: $PLUGIN_NAME\e[0m"
 
-# Running the plugins install command
-./update.sh
+  if [ ! -d "$PLUGIN_PATH/$PLUGIN_NAME" ]; then
+    echo "Error: Plugin '$PLUGIN_NAME' not found."
+    exit 1
+  fi
 
-notify-send "Plugin: $PLUGIN_NAME has been updated" -t 2000
+  cd "$PLUGIN_PATH/$PLUGIN_NAME"
+
+  # Running the plugins update script
+  ./update
+
+  ~/.local/share/omarchy/bin/omarchy-show-done
+fi
