fix: bash.curl.security.curl-pipe-bash.curl-pipe-bash-bin-omarchy-install-dev-env

diff --git a/bin/omarchy-install-dev-env b/bin/omarchy-install-dev-env
--- a/bin/omarchy-install-dev-env
+++ b/bin/omarchy-install-dev-env
@@ -124,7 +124,15 @@ zig)
   ;;
 ocaml)
   echo -e "Installing OCaml...\n"
-  bash -c "$(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
+    local rvm_installer
+    rvm_installer=$(mktemp)
+    trap 'rm -f "$rvm_installer"' EXIT
+    if curl -sSL https://get.rvm.io -o "$rvm_installer"; then
+      bash "$rvm_installer" -s stable
+    else
+      echo "Failed to download RVM installer." >&2
+      exit 1
+    fi
   opam init --yes
   eval "$(opam env)"
   opam install ocaml-lsp-server odoc ocamlformat utop --yes
